version: '3.8'

services:
  demo-ad-integration:
    image: ${DOCKER_REGISTRY}/${APP_NAME}:${IMAGE_TAG:-latest}
    container_name: demo-ad-integration
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      # API 配置通过环境变量传递
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL:-http://8.138.193.185:9080}
      - NUXT_PUBLIC_SSP_API_KEY=${NUXT_PUBLIC_SSP_API_KEY}
      - NUXT_PUBLIC_SSP_PRIVATE_KEY=${NUXT_PUBLIC_SSP_PRIVATE_KEY}
      - NUXT_PUBLIC_SSP_SLOT_ID=${NUXT_PUBLIC_SSP_SLOT_ID}
      - NUXT_PUBLIC_DSP_API_KEY=${NUXT_PUBLIC_DSP_API_KEY}
      - NUXT_PUBLIC_DSP_PRIVATE_KEY=${NUXT_PUBLIC_DSP_PRIVATE_KEY}
      - NUXT_PUBLIC_OPEN_API_SECRET=${NUXT_PUBLIC_OPEN_API_SECRET}
    networks:
      - ad-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ad-network:
    name: ad-network
    external: true

